### ISSUE TITLE
Create a readme.md explaining how to use the project (MVP)

### ISSUE THREAD

**Issue by keyy123** [keyy123/Project-Scrubz#6]
- [x] keyy123/Project-Scrubz#16
- [x] keyy123/Project-Scrubz#17
- [x] keyy123/Project-Scrubz#18
- [x] keyy123/Project-Scrubz#19
- [x] keyy123/Project-Scrubz#20
